[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"

[project]
name = "pytemplate"
version = "0.0.1"
description = "A python library"
dependencies = []
readme = "README.md"
requires-python = ">=3.14"
authors = [{ name = "Author", email = "author@email.com" }]

[project.scripts]
pytemplate = "pytemplate.main:main"

[dependency-groups]
dev = [
  { include-group = "docs" },
  { include-group = "lint" },
  { include-group = "test" },
]
docs = ["sphinx~=9.1.0"]
lint = ["prek~=0.3.11", "ruff~=0.15.12", "ty~=0.0.33"]
test = ["pytest~=9.0.3", "pytest-cov~=7.1.0"]

[tool.uv]
default-groups = ["dev"]
exclude-newer = "7 days"
exclude-newer-package = { urllib3 = false }

[project.urls]
Repository = "https://github.com/CQCL/pytemplate.git"

[tool.pytest.ini_options]
addopts = [
  "--cov=pytemplate",
  "--cov-report=term-missing",
  "--cov-fail-under=80",
]
testpaths = ["tests"]

[tool.ruff]
line-length = 100
target-version = "py314"
src = ["src"]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["COM812", "ISC001"]

[tool.ruff.lint.per-file-ignores]
"docs/*" = ["D100", "INP001"]
"tests/*" = ["ANN", "INP001", "PLR2004", "S101"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.coverage.run]
branch = true
source = ["src/pytemplate"]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "if TYPE_CHECKING:",
  "if __name__ == .__main__.:",
]

[tool.ty.terminal]
error-on-warning = true

[tool.ty.environment]
python-version = "3.14"

[tool.ty.rules]
possibly-unresolved-reference = "error"
unused-ignore-comment = "warn"
